name: EczemaPredNoteEnv
channels:
  - defaults
dependencies:
  - python=3.9
  - jupyter=1.0.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - scipy=1.10.1
  - matplotlib=3.7.1
  - numpy=1.23.5
  - pandas=2.2.2
  - scikit-learn=1.0.2
  - pip
  - pip:
    - scikit-learn 